### PR TITLE
small cleanup (semicolons) increased code coverage.

### PR DESCRIPTION
**Pull request by munxar**
added semicolons to pass jslint and reduce eye cancer on WebStorm IDE.
added coverage task to npm.
increased code coverage to 100%.

### CODE REVIEW

**Comment by kichooo** [comment]
Thank you for your Pull Request.

Before I merge it, resolve the issue with @syzer if you want semicolons or not, because god witnesses me that I'm dead tired of discussing semicolon or formatting issues and if I hear that once more god damn time I'm going to stop programming in nodejs altogether and switch to Go where there is only one way to format, as formatting is build in the compiler tooling.

**Comment by munxar** [comment]
removed semicolons. didn't know about the ongoing semicolon discussion.

**Comment by kichooo** [comment]
We plan to make the acc argument not required as soon as syzer finds a moment to code it properly as he promised :trollface: 

Merging

**Comment by syzer** [comment]
challenge accepted.

**Pull request merged**
